
executable = /bin/zsh
arguments = /nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/submit_nlp_sigbkg_2018/karim_calculation_ST_t-channel_top_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8/karim_calculation_ST_t-channel_top_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8_arraySubmit.sh
error  = /nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/submit_nlp_sigbkg_2018/karim_calculation_ST_t-channel_top_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8/logs/karim_calculation_ST_t-channel_top_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8submitScript.$(Cluster)_$(ProcId).err
log    = /nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/submit_nlp_sigbkg_2018/karim_calculation_ST_t-channel_top_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8/logs/karim_calculation_ST_t-channel_top_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8submitScript.$(Cluster)_$(ProcId).log
output = /nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/submit_nlp_sigbkg_2018/karim_calculation_ST_t-channel_top_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8/logs/karim_calculation_ST_t-channel_top_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8submitScript.$(Cluster)_$(ProcId).out
RequestMemory = 2000
RequestDisk = 2000000
+RequestRuntime = 10200
JobBatchName = karim_calculation_ST_t-channel_top_4f_InclusiveDecays_TuneCP5_13TeV-powheg-madspin-pythia8
RequestCpus = 1
Request_OpSysAndVer = "RedHat9"
getenv = True

Queue Environment From (
"SGE_TASK_ID=1"
"SGE_TASK_ID=2"
"SGE_TASK_ID=3"
"SGE_TASK_ID=4"
"SGE_TASK_ID=5"
"SGE_TASK_ID=6"
"SGE_TASK_ID=7"
"SGE_TASK_ID=8"
"SGE_TASK_ID=9"
"SGE_TASK_ID=10"
"SGE_TASK_ID=11"
"SGE_TASK_ID=12"
"SGE_TASK_ID=13"
"SGE_TASK_ID=14"
"SGE_TASK_ID=15"
"SGE_TASK_ID=16"
"SGE_TASK_ID=17"
"SGE_TASK_ID=18"
"SGE_TASK_ID=19"
"SGE_TASK_ID=20"
"SGE_TASK_ID=21"
"SGE_TASK_ID=22"
"SGE_TASK_ID=23"
"SGE_TASK_ID=24"
"SGE_TASK_ID=25"
"SGE_TASK_ID=26"
)