
universe = vanilla
executable = /bin/zsh
arguments = /nfs/dust/cms/user/larmbrus/combined_ttZ_ttH/karim/submit_reco_Z_chi2/karim_reconstruction_checkFiles.py/karim_reconstruction_checkFiles.py_arraySubmit.sh
error  = /nfs/dust/cms/user/larmbrus/combined_ttZ_ttH/karim/submit_reco_Z_chi2/karim_reconstruction_checkFiles.py/logs/karim_reconstruction_checkFiles.pysubmitScript.$(Cluster)_$(ProcId).err
log    = /nfs/dust/cms/user/larmbrus/combined_ttZ_ttH/karim/submit_reco_Z_chi2/karim_reconstruction_checkFiles.py/logs/karim_reconstruction_checkFiles.pysubmitScript.$(Cluster)_$(ProcId).log
output = /nfs/dust/cms/user/larmbrus/combined_ttZ_ttH/karim/submit_reco_Z_chi2/karim_reconstruction_checkFiles.py/logs/karim_reconstruction_checkFiles.pysubmitScript.$(Cluster)_$(ProcId).out
run_as_owner = true
Requirements = ( OpSysAndVer == "CentOS7" )
RequestMemory = 2000
RequestDisk = 2000000
+RequestRuntime = 7200
JobBatchName = karim_reconstruction_checkFiles.py

Queue Environment From (
)