
executable = /bin/zsh
arguments = /nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/submit_nlp_sigbkg_2018/karim_calculation_TTbb_4f_TTTo2L2Nu_TuneCP5-Powheg-Openloops-Pythia8_TopNanoAODv9/karim_calculation_TTbb_4f_TTTo2L2Nu_TuneCP5-Powheg-Openloops-Pythia8_TopNanoAODv9_arraySubmit.sh
error  = /nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/submit_nlp_sigbkg_2018/karim_calculation_TTbb_4f_TTTo2L2Nu_TuneCP5-Powheg-Openloops-Pythia8_TopNanoAODv9/logs/karim_calculation_TTbb_4f_TTTo2L2Nu_TuneCP5-Powheg-Openloops-Pythia8_TopNanoAODv9submitScript.$(Cluster)_$(ProcId).err
log    = /nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/submit_nlp_sigbkg_2018/karim_calculation_TTbb_4f_TTTo2L2Nu_TuneCP5-Powheg-Openloops-Pythia8_TopNanoAODv9/logs/karim_calculation_TTbb_4f_TTTo2L2Nu_TuneCP5-Powheg-Openloops-Pythia8_TopNanoAODv9submitScript.$(Cluster)_$(ProcId).log
output = /nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/submit_nlp_sigbkg_2018/karim_calculation_TTbb_4f_TTTo2L2Nu_TuneCP5-Powheg-Openloops-Pythia8_TopNanoAODv9/logs/karim_calculation_TTbb_4f_TTTo2L2Nu_TuneCP5-Powheg-Openloops-Pythia8_TopNanoAODv9submitScript.$(Cluster)_$(ProcId).out
RequestMemory = 2000
RequestDisk = 2000000
+RequestRuntime = 10200
JobBatchName = karim_calculation_TTbb_4f_TTTo2L2Nu_TuneCP5-Powheg-Openloops-Pythia8_TopNanoAODv9
RequestCpus = 1
Request_OpSysAndVer = "RedHat9"
getenv = True

Queue Environment From (
"SGE_TASK_ID=1"
"SGE_TASK_ID=2"
"SGE_TASK_ID=3"
)