
#!/bin/bash
subtasklist=(
/nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/nlp_sigbkg_2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9_7.sh
/nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/nlp_sigbkg_2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9_20.sh
/nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/nlp_sigbkg_2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9_24.sh
/nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/nlp_sigbkg_2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9_23.sh
/nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/nlp_sigbkg_2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9_18.sh
/nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/nlp_sigbkg_2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9_25.sh
/nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/nlp_sigbkg_2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9_27.sh
/nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/nlp_sigbkg_2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9_32.sh
/nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/nlp_sigbkg_2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9_31.sh
/nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/nlp_sigbkg_2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9_33.sh
/nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/nlp_sigbkg_2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9_4.sh
/nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/nlp_sigbkg_2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9_9.sh
/nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/nlp_sigbkg_2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9_17.sh
/nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/nlp_sigbkg_2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9_2.sh
/nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/nlp_sigbkg_2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9_13.sh
/nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/nlp_sigbkg_2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9_19.sh
/nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/nlp_sigbkg_2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9_6.sh
/nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/nlp_sigbkg_2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9_14.sh
/nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/nlp_sigbkg_2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9_34.sh
/nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/nlp_sigbkg_2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9_22.sh
/nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/nlp_sigbkg_2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9_3.sh
/nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/nlp_sigbkg_2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9_12.sh
/nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/nlp_sigbkg_2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9_21.sh
/nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/nlp_sigbkg_2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9_8.sh
/nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/nlp_sigbkg_2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9_11.sh
/nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/nlp_sigbkg_2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9_15.sh
/nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/nlp_sigbkg_2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9_16.sh
/nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/nlp_sigbkg_2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9_1.sh
/nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/nlp_sigbkg_2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9_29.sh
/nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/nlp_sigbkg_2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9_30.sh
/nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/nlp_sigbkg_2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9_10.sh
/nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/nlp_sigbkg_2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9_26.sh
/nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/nlp_sigbkg_2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9_28.sh
/nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/nlp_sigbkg_2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9_5.sh
/nfs/dust/cms/user/rrafeek/CMSSW_14_1_0_pre4/src/karim/workdir/shellscripts/nlp_sigbkg_2018/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_TopNanoAODv9_35.sh
)
thescript=${subtasklist[$SGE_TASK_ID]}
echo "starting dir: $PWD"
echo "${thescript}"
echo "$SGE_TASK_ID"
. $thescript
    